<%@ page language="java" pageEncoding="UTF-8" contentType="text/html;charset=UTF-8"%>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link href="${ctx}/css/easyui.css" rel="stylesheet" type="text/css" />
<link href="${ctx}/css/skin1.css" title="skin1" rel="stylesheet" type="text/css"/>
<link href="${ctx}/css/skin2.css" title="skin2" rel="stylesheet" type="text/css"/>
<link href="${ctx}/css/skin3.css" title="skin3" rel="stylesheet" type="text/css"/>
<link href="${ctx}/css/skin4.css" title="skin4" rel="stylesheet" type="text/css"/>
<link href="${ctx}/css/skin5.css" title="skin5" rel="stylesheet" type="text/css"/>
<link href="${ctx}/css/skin6.css" title="skin6" rel="stylesheet" type="text/css"/>