########api config###########
####api.server=http://openapi.shlefan.com/lefanfsapicenter/apicenter/{0}/{1}
api.server=http://localhost:8180/apicenter/{0}/{1}
api.key=98dba382bc9de1579f2e84d575608eda
api.secert=95cecbfa4fb491957186a5a609ec25fa

####### cache server ##############
memcache.cache.server=

file.server.url=http://openapi.shlefan.com/pic/images
file.server.rootDir=/data/webapps/pic/images
file.server.tempDir=/data/webapps/pic/images/temp
file.upload.imageMaxSize=5
file.upload.imageExt=jpg,jpeg,gif,png
file.upload.imageMimeType=image/jpeg,image/pjpeg,image/gif,image/png
file.upload.imageDefaultDirName=media/images
#####file.server=http://openapi.shlefan.com/pic/images
file.server=http://openapi.shlefan.com/pic/images
file.upload.videoMaxSize=100
file.upload.fileMaxSize=10
file.upload.imageType=jpg,jpeg,gif,png
file.upload.videoType=asx,asf,mpg,wmv,3gp,mp4,mov,avi,flv
file.upload.fileType=xlsx,rar,pdf,elx,elxs,doc,docx,mht,apk
ffmpeg.path=/data/soft/ffmpeg/ffmpeg
file.server.rootZipDir=/data/webapps/pic/zip

file.server.rootDir2=/mnt/sftp/files/
file.server.tempDir2=/mnt/sftp/files/temp/


# 读取超时（单位：毫秒）
http.client.read-timeout=120000

##\uFFFD\u04B4\uFFFD\uFFFD\uFFFD
survey_file_path=http://119.3.48.62:6077/ftp
file.survey.server=http://janitest.shlefan.com/ftp
file.survey.server.url=http://janitest.shlefan.com/ftp
file.survey.server.rootDir=/data/ftp
file.survey.server.rootZipDir=/data/ftp/zip
file.survey.server.tempDir=/data/ftp/temp
file.survey.upload.imageMaxSize=5
file.survey.upload.imageExt=jpg,jpeg,gif,png
file.survey.upload.imageMimeType=image/jpeg,image/pjpeg,image/gif,image/png
file.survey.upload.imageDefaultDirName=media/images
file.survey.upload.videoMaxSize=100
file.survey.upload.fileMaxSize=500
file.survey.upload.imageType=jpg,jpeg,gif,png
file.survey.upload.videoType=asx,asf,mpg,wmv,3gp,mp4,mov,avi,flv,silk
file.survey.upload.fileType=xlsx,rar,pdf,elx,elxs,doc,docx,mht,apk,silk,txt,xls,zip,jpg,jpeg,gif,png
file.survey.upload.fileType.new=jpg,doc,zip,rar,png,pdf,docx,m4a,mp3,xlsx,jpeg,xls,txt,mp4,amr,wav,7z,aac,3gpp,tif,gif,bmp,pptx,silk,mht,elx,elxs,apk
ffmpeg.survey.path=/data/soft/ffmpeg/ffmpeg

survey.file.source.sftp=/dev/
survey.file.path.sftp=http://119.3.48.62:6077/sftp/files/
survey.upload.ip=119.3.48.62
survey.upload.pwd=shlefan.com123

survey.report.path=D:/mnt/generate/report/
survey.direction.path=C:/direction/
survey.setting.source=dev
survey.temp.path=D:/mnt/generate/test/temp/

survey.account.path=C:/account/
survey.gonggu.path=C:/gonggu/
survey.transfer.path=C:/transfer/

redis_hostName=127.0.0.1
redis_port=6379
redis_password=shlefan.com123
redis_timeout=2000



http.fina.path=http://119.3.48.62:6077/sftp/files/

#nuanwa.company=P735002
#nuanwa.secret=f91223fa2d0ba12d

nuanwa.company=P55003
nuanwa.secret=f91223fa2d0ba12d