api.server=http://openapi.shlefan.com/lefancrmapicenter

##cdn config############################
#resource.prefix=http://resource.cargodd.com/
resource.prefix=http://openapi.shlefan.com/pic/images
user.default.icon=${resource.prefix}media/default-icon.jpg
user.default.cover=${resource.prefix}media/default-cover.jpg

img.host=http://openapi.shlefan.com/pic/images
####### file server ##############
file.server.url=http://openapi.shlefan.com/pic/images
file.server.rootDir=/data/webapps/pic/images
file.server.rootZipDir=/data/webapps/pic/zip
file.server.tempDir=/data/webapps/pic/images/temp
file.upload.imageMaxSize=5
file.upload.imageExt=jpg,jpeg,gif,png
file.upload.imageMimeType=image/jpeg,image/pjpeg,image/gif,image/png
file.upload.imageDefaultDirName=media/images
file.server=http://openapi.shlefan.com/pic/images
file.upload.videoMaxSize=100
file.upload.fileMaxSize=10
file.upload.imageType=jpg,jpeg,gif,png
file.upload.videoType=asx,asf,mpg,wmv,3gp,mp4,mov,avi,flv,silk
file.upload.fileType=xlsx,rar,pdf,elx,elxs,doc,docx,mht,apk,silk
ffmpeg.path=/data/soft/ffmpeg/ffmpeg



##leancloud#########################
leancloud.app.server=https://api.leancloud.cn/1.1
leancloud.app.id=jpjw0l73cfaia815nfeopl9rsvlcwg9zxbcl3849qwuuo86e
leancloud.app.key=efoz0yeakw6w30ltzsx9pz2rvpiottqv7w75y01re1yo4nwu

##rongcloud##################
rongcloud.app.key=x18ywvqf8fshc
rongcloud.app.secret=2zqYCoJy9uX4S
rongcloud.root.id=1

##kuaidi100##################
kuaidi100.viewLogisticsUrl=https://m.kuaidi100.com/index_all.html?type={0}&postid={1}#result

####### weixin config ##############
weixin.appid=wxbbf6ce54a66634cc
weixin.secret=d12c10dabb8fba0d5cf9afa3fa61880d
weixin.accessToken=https://api.weixin.qq.com/sns/oauth2/access_token?appid=${weixin.appid}&secret=${weixin.secret}&code={0}&grant_type=authorization_code
weixin.getUserInfo=https://api.weixin.qq.com/sns/userinfo?access_token={0}&openid={1}

######## weibo config######################
weibo.clientId=17578847
weibo.clientSecret=c685980359e0670fa5910e1c6b5d77a2
weibo.redirectUri=http://api.ccbaby.com/api/sns/weiboCallback

##jpush config ##############
jpush.appKey=00252741705a586ce8e658ea
jpush.masterSecret=4e42584fea81b7aafb868fe3

##alipay config #################
alipay.partner=2088521534003603
alipay.seller=runsheng5@sina.com
alipay.appId=2016122804684634
alipay.gateway=https://openapi.alipay.com/gateway.do
alipay.rsaPrivate=MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCRCnii8feVAbFa+dJOhXlJCm87yUrVeecXazy++6W9gKGSEr4Q8wdDyLoDkdFv8OM1CgaZ1nFLlEyS6Uh1P0fxBIQyMyxeJ0UtMUCxfi2dyaI0qi33vl0PU/5mxa75jBQSOHZSLtYw902TPfQpXG5GE1riT/q+Klcl1QHnwFUS+mudFn1twrNISL2XOuopnNx31gFYXzR+W6j6MvNo5CcxQF7764MyN9sM+Y8CWwntRasNXTBqSvXGuOlpGANguLffWEMYbYW1Vmvu9sJh/hiyCokksWDUYs19wBXAnxRG3BptbGC3FbvPtaJYqEA7YQd6SfIkdjiyfjK3UMxs4S8TAgMBAAECggEAH38+o2QYd+teMHuACD1EEXCKp1kXPzSx0owfLPpJC9YbQDWBwPyF31p/yran3L9bF/GNbWr8P4V8+4pdidisLtLkQmKKiAfPJflEK0dTcKiQ6Q7r3JkibGm5HWhgjyC0WyCX0VEKgqex2P/jPfgsmlspqWvk79cSBc00FLfXwb76P5//vp8/m45KtLIegcgP9NzDuEo16xYoijt3o2nItXYGNkxL6jAkZ2TOTzDjl/naJhP/ijMKqWUTzCwC4qEsM7nrzL97TrqVwTJYwSMb8Mezvk8OfAXcmI/6LYG7Lxx26QDWCI3g2cx8JF6m9aQWxec0XpH/fz8HWmqS/L/eAQKBgQDxPAtWV158JPrU9/YBkLqItCT6iJJ/LIgiga3SyPbE56G8dn4IDYpAxWyA0P1KHPncx/dgo5pKD2K032MgwIiZd96v8ey7dOZDSDHsux8af5SQWNLY7YobhprMEPAYgFNpDJETquG5ncwQ5FxEgy749n4HJtJgANmx+iRKaV1OMwKBgQCZ6yXt+8myjfkJzz7On/YCqNdLN7vCm24nWFumeQxkda0aUCOets8DVetaGcfl7o+wV0ZXE1fL3sU0FXAeFNGYxqCUnQS/D0MJgDOaciI/UHh7EAcrLI9wOyDr6HRCanGPdpcb89BChklMp3mvFkCC5RwsgXuWw8z22xITp137oQKBgQDEZrtgP1+4uS7Sp1LNsXR9ChW1N+31xl7LoULRAzcN1vwyAVLY4ZU26MVPF1ewuGihXNjGAE0EkQQu+FSvfLF6KULPgqrXb/RswOGMuEg5fbeJ0hdP8A1qHav4Cq4/dHL0avvOxGhkg9l5w0JvsVJT9fNjhTLwYKDcqyhSwPfrSwKBgB6iguYfG0ICp/Kf4SxXAiv9VvyNlz1gmkgSegtkRGcqVM3L7YsFb6aGT1WblAHbvZWniUSDgRH+wNlg+vPByQXTYtqxdeRhMUKO1baDyPU5GwHDaunY8KOx4ReTKLCfZwLa47CYknbrK2OqYbnLgAONflINY3/acM0hRTPMOBSBAoGATg8Z6blxbL9NbsEadIznPfMeKBn5uGJAlSPA6dC1TQ/QLTsyYA2b9uWPGdhZ+eA+YlkrRu/nJ4JxcZ+zbW0qMyLXMLjWpepFB4hEXu59ZvW6jPHhPrwcLwS2lGsm+4hGRRPuM3fJSLDOICAim94eAYsk7yQvFT5SwkNeALbYtoY=
alipay.rsaPublic=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDDI6d306Q8fIfCOaTXyiUeJHkrIvYISRcc73s3vF1ZT7XN8RNPwJxo8pWaJMmvyTn9N4HQ632qJBVHf8sxHi/fEsraprwCtzvzQETrNRwVxLO5jVmRGi60j8Ue1efIlzPXV9je9mkjzOmdssymZkh2QhUrCmZYI/FCEa3/cNMW0QIDAQAB
alipay.callbackUrl=${api.server}/api/payment/alipayCallback/{0}

##weixinpay config #################
weixinpay.appid=
weixinpay.key=
weixinpay.mchid=
weixinpay.unifiedorderUrl=https://api.mch.weixin.qq.com/pay/unifiedorder
weixinpay.orderqueryUrl=https://api.mch.weixin.qq.com/pay/orderquery
weixinpay.callbackUrl=${api.server}/api/payment/weixinpayCallback

##db config ##############
jdbc.driverClassName=com.mysql.jdbc.Driver
jdbc.url=jdbc:mysql://rm-uf66ux0sl812087hj.mysql.rds.aliyuncs.com:3306/lefan_es_test?useUnicode=true&amp;characterEncoding=utf-8&amp;allowMultiQueries=true
jdbc.maxActive=10
jdbc.maxIdle=3
jdbc.maxWait=10000
jdbc.initSize=20
jdbc.username=ddr
jdbc.password=DzBqKe6dp3Nz
jdbc.validationQuery=SELECT now()
jdbc.charset=set names utf8mb4;
executeTime=0


##cache server ##############
memcache.cache.server=127.0.0.1:11211

##redis server############################

redis.host=172.16.5.56
redis.port=6379
redis.password=CxwPiD4K7pbT
##redis.password=9OgjRSSfpSbDEiLc2abe

sms.expired.time=1801
sms.repeat.time=601


##weixin\u0421\uFFFD\uFFFD\uFFFD\uFFFDappId secret############################
mpwx_appId=wx698f1593ad128635
mpwx_secret=5245a8f8dbb788128ecd2557dd4810e8

##redis\uFFFD\uFFFD\uFFFD\u05B1\uFFFD\u02B6
redis_prefix=es


##\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD
##\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD
deductible_pro=0.1
##\uFFFD\uFFFD\u04BB\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u07B6\uFFFD
quota_one=10000
##\uFFFD\u06B6\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u07B6\uFFFD
quota_two=110000
##\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u07B6\uFFFD
quota_three=2000

##\uFFFD\uFFFD\u04BB\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u07B6\uFFFD
irresp_quota_one=1000
##\uFFFD\u06B6\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u07B6\uFFFD
irresp_quota_two=11000
##\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u07B6\uFFFD
irresp_quota_three=100
##\uFFFD\uDBA6\uDD37\uFFFD\uFFFD\u07B6\uFFFD
loss_word_fee=3500
##\u03A2\uFFFD\uFFFD\u0123\uFFFD\uFFFD\uFFFD\uFFFD\u03E2ID
wx_template_id=F01oGDhB-Z0v9oEhajkR2wF_BzQmNt-y8h4REcWgpks

##\u03A2\uFFFD\uFFFD\u0421\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u0276\uFFFD\u03AC\uFFFD\uFFFDurl
wx_qrcode_url=https://api.weixin.qq.com/cgi-bin/message/wxopen/template/send?access_token=
##\u03A2\uFFFD\uFFFD\u0421\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u0221tokenurl
wx_token_url=https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=
##\u03A2\uFFFD\uFFFD\u0421\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u0221\uFFFD\uFFFD\uFFFD\u0276\uFFFD\u03AC\uFFFD\uFFFD
create_wxa_qr_code=https://api.weixin.qq.com/cgi-bin/wxaapp/createwxaqrcode?access_token=

##\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u00FB\uFFFD\uFFFD\uFFFD
bk_username=topcar@sh-lefan.com
##\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD
bk_password=inscoo
##\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFDtokenURL
bk_token_url=http://api.inscoo.com/Token
##\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u057C\uFFFD\uFFFD\uFFFDURL
bk_memberins_url=http://api.inscoo.com/api/MemberInsurance/CreateMemberInsurance
##\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u05B9\uFFFD\uFFFD\uFFFD\uFFFDURL
bk_disabledate_url=http://api.inscoo.com/api/Product/GetDisableDate
##\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u0572\uFFFD\u01B7code
bk_product_code=1076

##\u0421\uFFFD\uFFFD\uFFFD\uFFFD\u036C\uFFFD\uFFFD\uFFFD\uFFFD\u05B7
xcx_url=http://openapi.shlefan.com/lefanfsapicenter/apitest/doApiTest

report_path_url=/data/webapps/pic/images/saas/

##\uFFFD\uFFFD\uFFFD\uFFFD\u05A7\uFFFD\uFFFD\uFFFD\u00B5\uFFFD\uFFFD\u04FF\uFFFDURL
suning_pay_url=https://ebankpay.suning.com/epps-ebpg/singleWithhold/paymentOrder.do
suning_pay_yifubao_file=/suning/yifubao_prd.cer

##\uFFFD\u05F8\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u03E2
suning_merchant_no=70210863
suning_public_key_index=0001
suning_version=2.0
suning_sign_algorithm=RSA
suning_input_charset=UTF-8
suning_order_type=01
suning_currency=CNY
suning_saler_merchant_no=70210863
suning_goods_type=521456
suning_pay_timeout=3d
suning_business_type=521456
suning_sub_merchant_no=70210863
suning_sub_merchant_name=70210863


#\u01BD\uFFFD\uFFFD\uFFFD\uFFFD
pingan.api.server=https://openapi.shlefan.com/lefanfsapicenter
pingan_server_returnURL=${pingan.api.server}/pingan/back
pingan_withHoldURL=https://caps.1qianbao.com/caps/request.do

##\u05E2\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u02FA\uFFFD(1)\uFFFD\uFFFD\uFFFD\u00F2\uFFFD\uFFFD\uFFFD
pingan_serviceCode=R0568
pingan_systemId=LEFAN
pingan_hashFunc=SHA-1
pingan_salt=
pingan_encrypt=AES
##\u05E2\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u02FA\uFFFD(2)
pingan_channel=Y-100054
pingan_system=\uFFFD\u05B7\uFFFD
pingan_coOperCode=0077
pingan_merchantNo=900000048481
pingan_partnerId=2000010003620066
##\uFFFD\uFFFD
pingan_bindCardVERSION=1.0
pingan_capital_index_card_no=32001881700052501851
pingan_capital_name=\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u0421\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u07B9\uFFFD\u02FE
pingan_key=DF84CBDCA294DC5DEF1368E64313FD3B98FE5EBCAB7D46AE
pingan_private_key=MIICdQIBADANBgkqhkiG9w0BAQEFAASCAl8wggJbAgEAAoGBAJaacx/zNxiMV8qe1Pot+b/GlPCZjbdsSxQb2pfZmvfqd8OBCOjPNcUZGkien34EVl90EXjn2omHTmwxFzwgvEnNXp3NBCxO6mGX03whLRo0GAoMT+HC7KELFYOwD1zx9IdEFol0ZlHOHSGGJJaS6c65s/gNcPG2OZSUaW6Hq4LFAgMBAAECgYAUTOlryxsIIhLLazGGL6BUq230KJ6jtONB6KdEhL6Q4HgYUFJlH1k+Ii4az9br46XI5Bpe09Hva9+0UcGyBy+aBjdoPs5AXvbq/GiyXb+GM3dEP1X77inVsnJCLqn5kN6vvuPeRz4VShyYraoM97bVYKzg6O6lud12PzDgr3672QJBAMSQvRX07+olSmLxZE54DdgffmWaVlzi2oYX73wBUBIavuUtgWbLQ/y462leqlo+0TN5quFXPq9UaagO+7QbRAcCQQDEI/1l53FU984kJH2GukQWB/h6id2UHxumyAHy59lw+E8E6bFujwqRD75r+v5tTKlEjdSu7JbJXhCIk0A358fTAkB5qGN/XXPH5YCesGy2rFNVOljOpbFiF/3MFLBifaWDLw6LZZi7eH8BwaniM3cYF9z/EQSUJ51igspJ+8wJcv6tAkBMhHnTqnHFIxNxeCbcS4hKS/u82lHt+iDQdNCF0bs7XjN9iCmnJviJVOoFuBpPy4txah9hynycvCyZC1EPPkXvAkAC7DdaLz+Stljiaf2qbnm1p2nCFPQU5UupZPMLGrg/TGo6pomWbaxHb2oocdUTNGO/AXPkPLrFLMoAlhj0UuJE

law_end_day=30


##\uFFFD\u04B4\uFFFD\uFFFD\uFFFD
survey.file.source.sftp=/product/
survey_file_path=https://ddrapi.shlefan.com/ftp
file.survey.server=http://ddrapi.shlefan.com/dimg
file.survey.server.url=http://ddrapi.shlefan.com/dimg
file.survey.server.rootDir=/data/webapps/dimg
file.survey.server.rootZipDir=/data/webapps/dimg/zip
file.survey.server.tempDir=/data/webapps/dimg/temp
file.survey.upload.imageMaxSize=5
file.survey.upload.imageExt=jpg,jpeg,gif,png
file.survey.upload.imageMimeType=image/jpeg,image/pjpeg,image/gif,image/png
file.survey.upload.imageDefaultDirName=media/images
file.survey.upload.videoMaxSize=100
file.survey.upload.fileMaxSize=10
file.survey.upload.imageType=jpg,jpeg,gif,png
file.survey.upload.videoType=asx,asf,mpg,wmv,3gp,mp4,mov,avi,flv,silk
file.survey.upload.fileType=xlsx,rar,pdf,elx,elxs,doc,docx,mht,apk,silk
ffmpeg.survey.path=/data/soft/ffmpeg/ffmpeg

survey_remote_url=https://ddrapi.shlefan.com/lefansurveyapicenter/apitest/doApiTest
survey.update.common=false
survey.role.one=6214
survey.role.two=26
survey.role.three=27
staff.users.not.score=298,318,335,564,566,567,572,611

survey.opr.user.no.help=2189
survey.opr.user.yes.safe=2189

survey.role.xiexiang=256
staff.users.not.examine=7190,6214,26,27
staff.users.not.send.wechat=7190,27

staff.users.zhangyongzhi=6501
staff.users.zhengyadong=7352


direction.text.error.baidu.appid=16869271
direction.text.error.baidu.appkey=588qfB74FiAVwVaFo521zE3q
direction.text.error.baidu.secretkey=42CAMiexhWVrEaGNOc7GmgXqSKbwCcTo

survey.role=50,57,58,98,114,116


http.fina.path=https://ddrapi.shlefan.com/sftp/files/

survey.setting.source=product
survey.report.path=/mnt/sftp/files/product/ddr/cno/
survey.file.path.sftp=https://ddrapi.shlefan.com/sftp/files

fina.messAge.url=http://saas.shlefan.com/crmbackend/

nw.appkey=GnWIFJpwT9olxkMX8CdYiKjZO9U1X4
nw.secretkey=vHgGQMB4mJXAvk58KHXAKhPhbkglRa
nw.spublickey=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCY8A9gKCjB5kBqxNUQn35ylFJCAv84U7xCsU+9vaKKtJ1t5ytRxUuk0Co6LNM8KB7OoM/ePwQbN5nav6E4SS4AHpXXY2rObHXg8BLM+5eKqHH/iwqQ7m1z4XT2dOsVAynesFUyggaFGeyr/wxlBJmavcK346xh0HHOfRDbc3g+DwIDAQAB
nw.url=https://gateway.nuanwa.net/gw/v2/offlineSupplier/fetchExecuteInfo
lf.cprivatekey=MIIBVQIBADANBgkqhkiG9w0BAQEFAASCAT8wggE7AgEAAkEAguiS6Pz9Zl0VnWnqZ1AHAvts72diL109i9HVffVOADT/x3g6OSOOl16RRgXTyU2OBuLNhH+PEUPOxlOdDaVtGQIDAQABAkAFc/66qd88ZmBCIGldSF4iZ6rQBjR22KF5s5H7Hz7Sj1ME/Eqz+KDa7klWzzo7zkDQZzzHS3izyYcHrKYFcYChAiEA4w/cHR5aGTLEQWGlefUqmeWikP5H6Mg0KLC5MgEAdlUCIQCTl5qkfO+j8hfBQSiNTo7sAPz79WiZagwyQYThAc+3tQIhAIInDybpxP94qCJKFI5Jx/ebN4ohF5sJV0yTsDRHerpZAiB9DlX/zcSXm4e5PeaIZOoA2o2BR91LMGoJIy7eIFTKiQIhAL9yrgbgupnmeYhseu7t42SY7r2q3y6s3/C48TTWrxhb
lf.cpublickey=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAILokuj8/WZdFZ1p6mdQBwL7bO9nYi9dPYvR1X31TgA0/8d4OjkjjpdekUYF08lNjgbizYR/jxFDzsZTnQ2lbRkCAwEAAQ==



down.http.path.claims=http://openapi.shlefan.com/
down.real.path.claims=/data/webapps/